name = "SimpleMotion"
license = "MIT"
licenselink = "https://github.com/simpleglobal/.sg-www/blob/main/LICENSE"
description = "Dark minimalist theme for SimpleMotion."
tags = ["minimal", "dark", "responsive", "company"]
min_version = "0.120.0"

[author]
  name = "SimpleMotion.Global"
  homepage = "https://new.simplemotion.global"
